### PR TITLE
MNIST digit classification notebook

### PR DESCRIPTION
**Pull request by ctrekker**
This pull request includes a notebook which evaluates a pretrained model (serialized in the file `mnist_conv.jls`). The model isn't very special, but the plan is to interface with it via WYSIWYR during my PlutoCon talk.

@fonsp I can include the notebook I used to train the notebook if that's something you want, but I figured it would probably best to just include a small binary file containing the pretrained model. I can add the notebook if you like. Also if the binary file is a problem I can just encode it inside the notebook instead.

### CODE REVIEW

**Comment by fonsp** [comment]
Awesome! How long does the training take?

**Comment by ctrekker** [comment]
> Awesome! How long does the training take?

The training is very short, taking about 10 minutes to achieve ~98% accuracy I think

**Comment by fonsp** [comment]
Okay! It would be better if you host the pretrained weight somewhere else on github and link to it via URL, i.e. `deserialize(download("https://..."))` so that people can run the notebook just by copy pasting its URL. It's also currently the "best practice" that we want to recommend to our users.

It might be interesting to use PlutoSliderServer (on your second repo, or we can do it here) to generate the weights file, that should actually just work out of the box, if you write the serialized file in the same folder as the notebook.

**Comment by ctrekker** [comment]
I've been having trouble getting that notebook to work with PlutoBindServer.jl. For some reason Flux gives me this error in the GitHub action but nowhere else: 
image

I did upload the model to http://cot.llc/mnist_conv and updated the notebook to download from that URL instead of depending on a local file.

**Comment by ctrekker** [comment]
I also committed my "Unbeatable Tic Tac Toe" notebook that I demoed for JuliaComputing. Since I've already built a full react app for it I figure it would be best to use that to demonstrate WYSIWYR being used outside Julia.

**Comment by fonsp** [comment]
> having trouble getting that notebook to work with PlutoBindServer.jl

I don't know how to help, maybe you need to pin the package versions: https://fonsp.com/article-test-3/pkghelper.html

**Pull request merged**
