### PR TITLE
add certificates notebook

### PR DESCRIPTION
**Pull request by Pangoraw**
Heyo!

This is a draft for the certificate generator notebook!
It is using [jsPDF](https://github.com/MrRio/jsPDF) under the hood to generate the PDF on the client side.
Unfortunately, this comes with a few limitations :grimacing: Mainly that SVGs are not supported and that images must be served with the header `access-control-allow-origin="*"` to be incuded in the PDF. Do you have an idea of where the image could be stored with such headers ?

### CODE REVIEW

**Comment by fonsp** [comment]
I found this: 
https://github.com/yWorks/svg2pdf.js

image

**Comment by fonsp** [comment]
About the headers, maybe you can generate a base64 url or a blob url instead? Try to find out how the demo website works

**Comment by Pangoraw** [comment]
> https://github.com/yWorks/svg2pdf.js

Nice! i will take a look

**Comment by Pangoraw** [comment]
> https://github.com/yWorks/svg2pdf.js

This is crisper! 

Example with "Julia Julia": 
[PlutoCon-Certificate.pdf](https://github.com/JuliaPluto/PlutoCon2021-demos/files/6260479/PlutoCon-Certificate.1.pdf)

**Comment by fonsp** [comment]
yessss this is awesome!! thank you!
I think i will tweak the SVG a little and then it's done, thanks!

**Pull request merged**
